package dsw.gerumap.app.message;

public enum EventType {

    ERROR, CANNOT_DELETE_PROJECT_EXPLORER, CANNOT_ADD_CHILD_TO_LEAF, NODE_NOT_SELECTED,
    PROJECT_NOT_SELECTED, MUST_INSERT_NAME, MUST_SET_AUTHOR, BLANK_NAME, MUST_INSERT_TEXT, ENTER_INTEGER,
    SELECT_ELEMENTS, OPEN_MIND_MAP, INVALID_SIZE, INVALID_NAME_SIZE, OPEN_FAIL, SAVE_FAIL;

}
